apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  gateway-secret-key: change-this-gateway-secret-min-16
  hmac-secret: change-this-hmac-secret-min-32
  jwt-secret: change-this-jwt-secret-min-32
  jwt-refresh-secret: change-this-jwt-refresh-secret-min-32
  realtime-api-key: change-this-realtime-api-key
