apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-trail-server
  labels:
    app: audit-trail-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: audit-trail-server
  template:
    metadata:
      labels:
        app: audit-trail-server
    spec:
      containers:
        - name: audit-trail-server
          image: daev681/daev681:audit-trail-server
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: postgres-database-url
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
      imagePullSecrets:
        - name: my-secret
