apiVersion: apps/v1
kind: Deployment
metadata:
  name: gm-tool-server
  labels:
    app: gm-tool-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gm-tool-server
  template:
    metadata:
      labels:
        app: gm-tool-server
    spec:
      containers:
        - name: gm-tool-server
          image: daev681/daev681:gm-tool-server
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
      imagePullSecrets:
        - name: my-secret
