apiVersion: v1
kind: Service
metadata:
  name: realtime-server-service
spec:
  selector:
    app: realtime-server
  ports:
    - name: game
      protocol: TCP
      port: 7777
      targetPort: 7777
    - name: health
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
