apiVersion: v1
kind: Service
metadata:
  name: world-zone-server-service
spec:
  selector:
    app: world-zone-server
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
