apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "api-server"
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ["api-server-service:8080"]

      - job_name: "api-gateway-readiness"
        metrics_path: /readyz
        static_configs:
          - targets: ["api-gateway-service:80"]

      - job_name: "realtime-server"
        metrics_path: /metrics
        static_configs:
          - targets: ["realtime-server-service:8081"]
